FROM continuumio/miniconda3:latest

SHELL ["/bin/bash", "-c"]

# Configure channels
RUN conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda config --add channels defaults && \
    conda config --set channel_priority flexible

# Create environment with all pins + compilers
RUN conda create -y -n rhizosmash \
    python=3.10 \
    gcc \
    gxx \
    make \
    boost-cpp=1.74.0 \
    libzlib=1.2.13 \
    hmmer2=2.3.2 \
    hmmer=3.4 \
    diamond=2.0.15 \
    fasttree=2.1.11 \
    prodigal=2.6.3 \
    blast=2.16.0 \
    muscle=5.1 \
    glimmerhmm=3.0.4 && \
    conda clean -afy

# Make conda env active by default
ENV CONDA_DEFAULT_ENV=rhizosmash
ENV PATH=/opt/conda/envs/rhizosmash/bin:$PATH

# Install rhizoSMASH
WORKDIR /opt
RUN git clone https://git.wur.nl/yuze.li/rhizosmash.git && \
    cd rhizosmash && \
    pip install .

# Download databases
RUN download-rhizosmash-databases

CMD ["bash"]


